/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Items
         * @description List items for the current user.
         */
        get: operations["list_items_api_v1_items_get"];
        put?: never;
        /**
         * Create Item
         * @description Create a new item.
         */
        post: operations["create_item_api_v1_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Item
         * @description Get a specific item by ID.
         */
        get: operations["get_item_api_v1_items__item_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Item
         * @description Delete an item (owner only).
         */
        delete: operations["delete_item_api_v1_items__item_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Item
         * @description Update an existing item (owner only).
         */
        patch: operations["update_item_api_v1_items__item_id__patch"];
        trace?: never;
    };
    "/api/v1/items/{item_id}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Share Item
         * @description Share an item to specified bubbles (replaces existing shares).
         */
        post: operations["share_item_api_v1_items__item_id__share_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User
         * @description Get the current user's profile.
         */
        get: operations["get_current_user_api_v1_user_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Current User
         * @description Update the current user's profile.
         */
        patch: operations["update_current_user_api_v1_user_me_patch"];
        trace?: never;
    };
    "/api/v1/user/check-username/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Username
         * @description Check if a username is available.
         */
        get: operations["check_username_api_v1_user_check_username__username__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Setup Profile
         * @description Initial profile setup for new users.
         *
         *     Creates a user profile if it doesn't exist.
         */
        post: operations["setup_profile_api_v1_user_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bubbles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Bubbles
         * @description List all bubbles the current user is a member of.
         */
        get: operations["list_bubbles_api_v1_bubbles_get"];
        put?: never;
        /**
         * Create Bubble
         * @description Create a new bubble.
         */
        post: operations["create_bubble_api_v1_bubbles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bubbles/{bubble_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Bubble
         * @description Get a specific bubble by ID.
         */
        get: operations["get_bubble_api_v1_bubbles__bubble_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Bubble
         * @description Delete a bubble (admin only).
         */
        delete: operations["delete_bubble_api_v1_bubbles__bubble_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Bubble
         * @description Update a bubble (admin only).
         */
        patch: operations["update_bubble_api_v1_bubbles__bubble_id__patch"];
        trace?: never;
    };
    "/api/v1/bubbles/join/{invite_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join Bubble
         * @description Join a bubble using an invite code.
         */
        post: operations["join_bubble_api_v1_bubbles_join__invite_code__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bubbles/{bubble_id}/regenerate-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate Invite Code
         * @description Regenerate the invite code for a bubble (admin only).
         */
        post: operations["regenerate_invite_code_api_v1_bubbles__bubble_id__regenerate_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bubbles/{bubble_id}/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Member
         * @description Remove a member from a bubble (admin only, or self-remove).
         */
        delete: operations["remove_member_api_v1_bubbles__bubble_id__members__member_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Member Role
         * @description Update a member's role (admin only).
         */
        patch: operations["update_member_role_api_v1_bubbles__bubble_id__members__member_id__patch"];
        trace?: never;
    };
    "/api/v1/loans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Loans
         * @description List loans related to the current user.
         *
         *     By default shows all loans (both as borrower and lender).
         *     Use as_borrower=true or as_lender=true to filter.
         */
        get: operations["list_loans_api_v1_loans_get"];
        put?: never;
        /**
         * Request Loan
         * @description Request to borrow an item.
         */
        post: operations["request_loan_api_v1_loans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{loan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Loan
         * @description Get a specific loan by ID.
         */
        get: operations["get_loan_api_v1_loans__loan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Loan
         * @description Update a loan status.
         *
         *     - Owner can: approve (requested -> active), mark returned (active -> returned)
         *     - Borrower can: cancel (requested -> cancelled), mark returned (active -> returned)
         */
        patch: operations["update_loan_api_v1_loans__loan_id__patch"];
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Basic health check endpoint.
         *
         *     Returns 200 if the API is running.
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check Db
         * @description Database health check endpoint.
         *
         *     Verifies connectivity to Supabase by running a simple query.
         *     Returns 200 if database is accessible, 503 otherwise.
         */
        get: operations["health_check_db_api_health_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Bubble
         * @description Response model for a bubble.
         */
        Bubble: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Invite Code */
            invite_code: string;
            /** Created By */
            created_by: string;
            /** Created At */
            created_at: string;
        };
        /**
         * BubbleCreate
         * @description Request model for creating a bubble.
         */
        BubbleCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /**
         * BubbleInvite
         * @description Response for joining via invite code.
         */
        BubbleInvite: {
            bubble: components["schemas"]["Bubble"];
            /** Message */
            message: string;
        };
        /**
         * BubbleList
         * @description List of bubbles.
         */
        BubbleList: {
            /** Bubbles */
            bubbles: components["schemas"]["BubbleWithMembers"][];
            /** Total */
            total: number;
        };
        /**
         * BubbleRef
         * @description Reference to a bubble.
         */
        BubbleRef: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * BubbleRefSimple
         * @description Simple reference to a bubble.
         */
        BubbleRefSimple: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * BubbleUpdate
         * @description Request model for updating a bubble.
         */
        BubbleUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * BubbleWithMembers
         * @description Bubble with member information.
         */
        BubbleWithMembers: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Invite Code */
            invite_code: string;
            /** Created By */
            created_by: string;
            /** Created At */
            created_at: string;
            /**
             * Members
             * @default []
             */
            members: components["schemas"]["MemberRef"][];
            /**
             * Member Count
             * @default 0
             */
            member_count: number;
            /**
             * Is Admin
             * @default false
             */
            is_admin: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ItemCreate
         * @description Request model for creating an item.
         */
        ItemCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
        };
        /**
         * ItemList
         * @description Paginated list of items.
         */
        ItemList: {
            /** Items */
            items: components["schemas"]["ItemWithShares"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Limit */
            limit: number;
        };
        /**
         * ItemRef
         * @description Reference to an item.
         */
        ItemRef: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /**
         * ItemShare
         * @description Request model for sharing an item to bubbles.
         */
        ItemShare: {
            /** Bubble Ids */
            bubble_ids: string[];
        };
        /**
         * ItemUpdate
         * @description Request model for updating an item.
         */
        ItemUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Quantity */
            quantity?: number | null;
        };
        /**
         * ItemWithShares
         * @description Item with shared bubbles info.
         */
        ItemWithShares: {
            /** Id */
            id: string;
            /** Owner Id */
            owner_id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
            /** Created At */
            created_at: string;
            /**
             * Shared Bubbles
             * @default []
             */
            shared_bubbles: components["schemas"]["BubbleRef"][];
            /**
             * Available Quantity
             * @default 0
             */
            available_quantity: number;
        };
        /**
         * LoanList
         * @description List of loans.
         */
        LoanList: {
            /** Loans */
            loans: components["schemas"]["LoanWithDetails"][];
            /** Total */
            total: number;
        };
        /**
         * LoanRequest
         * @description Request model for requesting to borrow an item.
         */
        LoanRequest: {
            /** Item Id */
            item_id: string;
            /** Bubble Id */
            bubble_id: string;
            /** Notes */
            notes?: string | null;
        };
        /**
         * LoanUpdate
         * @description Request model for updating a loan status.
         */
        LoanUpdate: {
            /**
             * Status
             * @enum {string}
             */
            status: "requested" | "active" | "returned" | "cancelled";
            /** Notes */
            notes?: string | null;
        };
        /**
         * LoanWithDetails
         * @description Loan with full entity details.
         */
        LoanWithDetails: {
            /** Id */
            id: string;
            /** Item Id */
            item_id: string;
            /** Borrower Id */
            borrower_id: string;
            /** Bubble Id */
            bubble_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "requested" | "active" | "returned" | "cancelled";
            /** Requested At */
            requested_at: string;
            /** Lent At */
            lent_at?: string | null;
            /** Returned At */
            returned_at?: string | null;
            /** Notes */
            notes?: string | null;
            item: components["schemas"]["ItemRef"];
            borrower: components["schemas"]["UserRef"];
            bubble: components["schemas"]["BubbleRefSimple"];
            owner: components["schemas"]["UserRef"];
        };
        /**
         * MemberRef
         * @description Reference to a member in a bubble.
         */
        MemberRef: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /** Username */
            username?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "member";
            /** Joined At */
            joined_at: string;
        };
        /**
         * UpdateMemberRole
         * @description Request model for updating a member's role.
         */
        UpdateMemberRole: {
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "member";
        };
        /**
         * UserProfile
         * @description User profile response model.
         */
        UserProfile: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /** Username */
            username?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
            /** Created At */
            created_at: string;
        };
        /**
         * UserProfileUpdate
         * @description Request model for updating user profile.
         */
        UserProfileUpdate: {
            /** Display Name */
            display_name?: string | null;
            /** Username */
            username?: string | null;
        };
        /**
         * UserRef
         * @description Reference to a user.
         */
        UserRef: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /** Username */
            username?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
        };
        /**
         * UsernameCheck
         * @description Response for username availability check.
         */
        UsernameCheck: {
            /** Username */
            username: string;
            /** Available */
            available: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_items_api_v1_items_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_item_api_v1_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemWithShares"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_api_v1_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemWithShares"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_api_v1_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_item_api_v1_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemWithShares"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    share_item_api_v1_items__item_id__share_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemShare"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemWithShares"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_api_v1_user_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    update_current_user_api_v1_user_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_username_api_v1_user_check_username__username__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsernameCheck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    setup_profile_api_v1_user_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bubbles_api_v1_bubbles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BubbleList"];
                };
            };
        };
    };
    create_bubble_api_v1_bubbles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BubbleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BubbleWithMembers"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bubble_api_v1_bubbles__bubble_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bubble_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BubbleWithMembers"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_bubble_api_v1_bubbles__bubble_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bubble_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_bubble_api_v1_bubbles__bubble_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bubble_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BubbleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bubble"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_bubble_api_v1_bubbles_join__invite_code__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invite_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BubbleInvite"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_invite_code_api_v1_bubbles__bubble_id__regenerate_code_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bubble_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bubble"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_api_v1_bubbles__bubble_id__members__member_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bubble_id: string;
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_member_role_api_v1_bubbles__bubble_id__members__member_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bubble_id: string;
                member_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberRole"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberRef"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_loans_api_v1_loans_get: {
        parameters: {
            query?: {
                /** @description Filter by status */
                status?: string;
                /** @description Show loans where I'm the borrower */
                as_borrower?: boolean;
                /** @description Show loans where I'm the lender */
                as_lender?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_loan_api_v1_loans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanWithDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_loan_api_v1_loans__loan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanWithDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_loan_api_v1_loans__loan_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoanUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanWithDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_db_api_health_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
