/**
 * Authentication fixtures for E2E tests
 *
 * Provides authenticated test contexts using seeded test users.
 * Uses Supabase signInWithPassword for real token generation.
 */

import { test as base, expect, APIRequestContext } from '@playwright/test'
import { createClient, SupabaseClient } from '@supabase/supabase-js'

// Local Supabase configuration (from api/supabase/config.toml)
const SUPABASE_URL = 'http://localhost:64321'
// Standard local development anon key (generated by supabase start)
const SUPABASE_ANON_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0'

export const API_BASE_URL = 'http://localhost:9990'
export const FRONTEND_URL = process.env.FRONTEND_URL || 'http://localhost:6174'

/**
 * Test users from seed data (api/supabase/seed/seed.sql)
 * All users have password: 'password123'
 */
export const TEST_USERS = {
  alice: {
    email: 'alice@example.com',
    password: 'password123',
    id: '10000000-0000-0000-0000-000000000001',
    displayName: 'Alice Johnson',
    username: 'alice',
  },
  bob: {
    email: 'bob@example.com',
    password: 'password123',
    id: '10000000-0000-0000-0000-000000000002',
    displayName: 'Bob Smith',
    username: 'bob',
  },
  carol: {
    email: 'carol@example.com',
    password: 'password123',
    id: '10000000-0000-0000-0000-000000000003',
    displayName: 'Carol Davis',
    username: 'carol',
  },
} as const

export type TestUserName = keyof typeof TEST_USERS

// Cache for auth tokens to avoid repeated sign-ins
const tokenCache = new Map<string, { token: string; expiresAt: number }>()

/**
 * Get a Supabase client for authentication
 */
function getSupabaseClient(): SupabaseClient {
  return createClient(SUPABASE_URL, SUPABASE_ANON_KEY)
}

/**
 * Sign in as a test user and get their access token
 */
export async function getAuthToken(user: TestUserName = 'alice'): Promise<string> {
  const userInfo = TEST_USERS[user]
  const cacheKey = userInfo.email

  // Check cache first (tokens valid for ~1 hour, refresh after 50 min)
  const cached = tokenCache.get(cacheKey)
  if (cached && cached.expiresAt > Date.now()) {
    return cached.token
  }

  const supabase = getSupabaseClient()

  const { data, error } = await supabase.auth.signInWithPassword({
    email: userInfo.email,
    password: userInfo.password,
  })

  if (error || !data.session) {
    throw new Error(
      `Failed to sign in as ${user}: ${error?.message || 'No session returned'}`
    )
  }

  const token = data.session.access_token

  // Cache token for 50 minutes (tokens typically valid for 1 hour)
  tokenCache.set(cacheKey, {
    token,
    expiresAt: Date.now() + 50 * 60 * 1000,
  })

  return token
}

/**
 * Create an authenticated request helper
 */
function createAuthenticatedRequest(
  request: APIRequestContext,
  token: string
) {
  return {
    get: (url: string, options?: Parameters<APIRequestContext['get']>[1]) =>
      request.get(url, {
        ...options,
        headers: {
          ...options?.headers,
          Authorization: `Bearer ${token}`,
        },
      }),

    post: (url: string, options?: Parameters<APIRequestContext['post']>[1]) =>
      request.post(url, {
        ...options,
        headers: {
          ...options?.headers,
          Authorization: `Bearer ${token}`,
        },
      }),

    patch: (url: string, options?: Parameters<APIRequestContext['patch']>[1]) =>
      request.patch(url, {
        ...options,
        headers: {
          ...options?.headers,
          Authorization: `Bearer ${token}`,
        },
      }),

    put: (url: string, options?: Parameters<APIRequestContext['put']>[1]) =>
      request.put(url, {
        ...options,
        headers: {
          ...options?.headers,
          Authorization: `Bearer ${token}`,
        },
      }),

    delete: (url: string, options?: Parameters<APIRequestContext['delete']>[1]) =>
      request.delete(url, {
        ...options,
        headers: {
          ...options?.headers,
          Authorization: `Bearer ${token}`,
        },
      }),
  }
}

export type AuthenticatedRequest = ReturnType<typeof createAuthenticatedRequest>

/**
 * Extended test fixture with single authenticated user (Alice by default)
 */
export const test = base.extend<{
  authToken: string
  authRequest: AuthenticatedRequest
  currentUser: (typeof TEST_USERS)['alice']
}>({
  authToken: async ({}, use) => {
    const token = await getAuthToken('alice')
    await use(token)
  },

  authRequest: async ({ request, authToken }, use) => {
    const authenticatedRequest = createAuthenticatedRequest(request, authToken)
    await use(authenticatedRequest)
  },

  currentUser: async ({}, use) => {
    await use(TEST_USERS.alice)
  },
})

/**
 * Multi-user test fixture for RLS and permission testing
 */
export const multiUserTest = base.extend<{
  aliceToken: string
  bobToken: string
  carolToken: string
  aliceRequest: AuthenticatedRequest
  bobRequest: AuthenticatedRequest
  carolRequest: AuthenticatedRequest
}>({
  aliceToken: async ({}, use) => {
    const token = await getAuthToken('alice')
    await use(token)
  },

  bobToken: async ({}, use) => {
    const token = await getAuthToken('bob')
    await use(token)
  },

  carolToken: async ({}, use) => {
    const token = await getAuthToken('carol')
    await use(token)
  },

  aliceRequest: async ({ request, aliceToken }, use) => {
    const authenticatedRequest = createAuthenticatedRequest(request, aliceToken)
    await use(authenticatedRequest)
  },

  bobRequest: async ({ request, bobToken }, use) => {
    const authenticatedRequest = createAuthenticatedRequest(request, bobToken)
    await use(authenticatedRequest)
  },

  carolRequest: async ({ request, carolToken }, use) => {
    const authenticatedRequest = createAuthenticatedRequest(request, carolToken)
    await use(authenticatedRequest)
  },
})

export { expect }
